### ISSUE TITLE
ASTRA python 3.5 under python 3.6, Windows 

### ISSUE THREAD

**Issue by NathanaelSix** [astra-toolbox/astra-toolbox#134]
Downloaded precompiled python version of the astra toolbox and placed in anaconda3/Lib/site-packages/astra

When running example file s001_sinogram_par2d.py I get the error:
```
Traceback (most recent call last):
  File "C:/Users/nsix/Downloads/astra-1.8/samples/s001_sinogram_par2d.py", line 26, in <module>
    import astra
  File "C:\Users\nsix\AppData\Local\Continuum\Anaconda3\lib\site-packages\astra\__init__.py", line 26, in <module>
    from . import matlab as m
  File "C:\Users\nsix\AppData\Local\Continuum\Anaconda3\lib\site-packages\astra\matlab.py", line 38, in <module>
    from . import astra_c
ImportError: DLL load failed: The specified module could not be found.
```

This was after changing the names of the .pyd dlls from *.cp35-win_amd64.pyd to *.pyd, before doing that, it couldn't even find astra_c.

pip install astra-toolbox also fails.

(The precompiled matlab version of the astra toolbox does work on the same machine)

**Comment by NathanaelSix** [comment]
conda install did work
