### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by JulianWi21** [astra-toolbox/astra-toolbox#231]
Hi all,

I am trying to install the astra-toolbox on Python 3.7.6 64 bit on Windows 10 Spyder 4.0.1. However installing the astra-toolbox with the **pip install astra-toolbox** command results in the following errors:

```
Collecting astra-toolbox
  Using cached astra-toolbox-1.8b5.tar.gz (452 kB)
Requirement already satisfied: numpy in c:\users\wittmajn\anaconda3\lib\site-packages (from astra-toolbox) (1.18.1)
Requirement already satisfied: six in c:\users\wittmajn\appdata\roaming\python\python37\site-packages (from astra-toolbox) (1.12.0)
Requirement already satisfied: scipy in c:\users\wittmajn\anaconda3\lib\site-packages (from astra-toolbox) (1.4.1)
Requirement already satisfied: cython in c:\users\wittmajn\anaconda3\lib\site-packages (from astra-toolbox) (0.29.15)
Building wheels for collected packages: astra-toolbox
  Building wheel for astra-toolbox (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\wittmajn\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wittmajn\\AppData\\Local\\Temp\\pip-install-kjqje4fc\\astra-toolbox\\setup.py'"'"'; __file__='"'"'C:\\Users\\wittmajn\\AppData\\Local\\Temp\\pip-install-kjqje4fc\\astra-toolbox\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\wittmajn\AppData\Local\Temp\pip-wheel-omca8had'
       cwd: C:\Users\wittmajn\AppData\Local\Temp\pip-install-kjqje4fc\astra-toolbox\
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\wittmajn\AppData\Local\Temp\pip-install-kjqje4fc\astra-toolbox\setup.py", line 76, in <module>
      subprocess.call(['./autogen.sh'])
    File "C:\Users\wittmajn\Anaconda3\lib\subprocess.py", line 339, in call
      with Popen(*popenargs, **kwargs) as p:
    File "C:\Users\wittmajn\Anaconda3\lib\subprocess.py", line 800, in __init__
      restore_signals, start_new_session)
    File "C:\Users\wittmajn\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
      startupinfo)
  OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
  ----------------------------------------
  ERROR: Failed building wheel for astra-toolbox
```

As an alternative I've also tried the command **conda install -c astra-toolbox astra-toolbox** resulting in the following error message:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - astra-toolbox -> python[version='2.7.*|3.5.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.6.*']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==8.0=0
  - feature:|@/win-64::__cuda==8.0=0

Your installed CUDA driver is: 8.0
```

I would highly appreciate some hints or help regarding this problem.

**Comment by megalinier** [comment]
Hello, 
I have the same problem... Have you managed to fix it?

**Comment by whywww** [comment]
You need to switch to python 3.6 or 3.5

**Comment by testitkvtk** [comment]
Yes the cause for this error was that the nvidia graphics card on my pc and the installed cuda driver were incompatible. Or in other words my nvidia graphics card was too old and had a too low CUDA Compute Capability. Had no other choice and switch to a pc with a more recent nvidia graphics card that fulfills the CUDA Compute Capability of the installed CUDA driver. Hope this helps.
