### ISSUE TITLE
Documentation gives wrong information

### ISSUE THREAD

**Issue by meetaig** [astra-toolbox/astra-toolbox#279]
Some of the documentation is showing that a projector object is required for execution, but it is not mentioned in the examples

http://astra-toolbox.com/docs/algs/FBP_CUDA.html
http://astra-toolbox.com/docs/algs/SART_CUDA.html

I assume this is just a copy paste error, as those are both algorithms that have non-CUDA counterparts.

Additionally FP3D_CUDA, BP3D_CUDA and EM_CUDA are not documented at all.

It would also be a nice addition to get a more telling error message when giving a wrong configuration for an algorithm. For example, an algorithm that does not get a ProjectorId, but requires one, does not tell me that it needs one. It just tells me that it was not able to initialize the algorithm.

**Comment by wjp** [comment]
Regarding the last point: we should already be printing an error message pointing out the missing value. E.g., from python:

```
Configuration Error in Reconstruction2D: No ProjectorId tag specified.
Traceback (most recent call last):
  File "s004_cpu_reconstruction.py", line 64, in <module>
    alg_id = astra.algorithm.create(cfg)
  File "/home/wjp/pkgs/miniconda3/envs/astra-git/lib/python3.7/site-packages/astra/algorithm.py", line 36, in create
    return a.create(config)
  File "astra/algorithm_c.pyx", line 68, in astra.algorithm_c.create
Exception: Unable to initialize Algorithm.
```

Although it's also true that the traceback kind of hides it. Worth considering if the error can be folded into the exception itself. Does the way you run astra hide the message? We should see if we can figure out why.

**Comment by maggie2209** [comment]
Hello, I've just seen this and I was wondering if this has been fixed? I am still getting the error with the ProjectorId tag and not sure what to change in my code. I am new to astra, so maybe I am misunderstanding. I want to reconstruct an image from a sinogram using BP (the sinogram is imported into astra, so I didn't use create_sino()). This is the snippet where I get the error. Do you have an idea where I went wrong?
recon_id=astra.data2d.create('-vol', vol_geom)
cfg=astra.astra_dict('BP')
cfg['ReconstructionDataId']=recon_id
cfg['ProjectionDataId']=proj_id
alg_id=astra.algorithm.create(cfg)

**Comment by askorikov** [comment]
@maggie2209 That's probably because you pass sinogram as a Numpy object, whereas an Astra object is expected. Please feel free to open a new discussion if that's still relevant.
