### ISSUE TITLE
How can I import my own data(sinogram data ) to reconstruction? 

### ISSUE THREAD

**Issue by jinxiqinghuan** [astra-toolbox/astra-toolbox#298]
In all the examples, the sinogram obtained by the phantom256 front projection is used for reconstruction. Now, I want to use my own sinogram reconstruction, how should I import the data? When i import by this way:

```python
ol_geom = astra.create_vol_geom(180, 70)
import scipy.io
# sinogram.mat is my data with the shape(180, 70) while the 180 is the angle 
my_sinogram = scipy.io.loadmat('sinogram.mat')['sinogram']
sinogram_id = astra.data2d.create('-vol', vol_geom, my_sinogram)
# sinogram_id = astra.data2d.create('-sino', my_sinogram)
```
and the error give me: 

```python
Configuration Error in FBP_CUDA: Invalid Projection Data Object.
Traceback (most recent call last):
  File "d:/ljt/Study/Madic/NEMA/Learn_Code/astra/astra-toolbox/samples/python/s000.py", line 48, in <module>
    alg_id = astra.algorithm.create(cfg)
  File "C:\Users\lyu\.conda\envs\fbp\lib\site-packages\astra\algorithm.py", line 36, in create
    return a.create(config)
  File "astra\algorithm_c.pyx", line 61, in astra.algorithm_c.create
Exception: Unable to initialize Algorithm.
```

Thank you very much!

**Comment by jinxiqinghuan** [comment]
If I import the sinogram data directly by this way:
```python
vol_geom = astra.create_vol_geom(180, 70)
import scipy.io
# sinogram.mat is my data with the shape(180, 70) while the 180 is the angle 
my_sinogram = scipy.io.loadmat('sinogram.mat')['sinogram']
sinogram_id = astra.data2d.create('-sino', my_sinogram)

rec_id = astra.data2d.create('-vol', vol_geom)

# create configuration 
cfg = astra.astra_dict('FBP_CUDA')
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = sinogram_id
cfg['option'] = { 'FilterType': 'Ram-Lak' }
```
the following error will appear:

```python
IndexError: arrays used as indices must be of integer (or boolean) type
Exception ignored in: 'astra.utils.readDict'
IndexError: arrays used as indices must be of integer (or boolean) type
Configuration Error in ProjectionGeometry2D: No DetectorWidth tag specified.
Configuration Error in ProjectionGeometry2D: Detector Count should be positive.
Traceback (most recent call last):
  File "d:/ljt/Study/Madic/NEMA/Learn_Code/astra/astra-toolbox/samples/python/s000.py", line 16, in <module>
    sinogram_id = astra.data2d.create('-sino', my_sinogram)
  File "C:\Users\lyu\.conda\envs\fbp\lib\site-packages\astra\data2d.py", line 54, in create
    return d.create(datatype,geometry,data)
  File "astra\data2d_c.pyx", line 119, in astra.data2d_c.create
RuntimeError: Geometry class not initialized.
```

**Comment by MaxBe23** [comment]
Hey, 

for 

`sinogram_id = astra.data2d.create('-sino', my_sinogram)`

you need you projection geometry, which you can produce with: 

`astra.create_proj_geom`

then look into the doc: 

[Doc Astra](https://www.astra-toolbox.com/apiref/creators.html)

Which type of geometry you have and then fill in all your stuff. 

`vol_geom = astra.create_vol_geom(180, 70)`

This line is just for the reconstruction volume and not for your sinogram. 

Cheers

**Comment by jinxiqinghuan** [comment]
Deer MaxBe23,
 It's really helped me. 😃 Thank you for your kindness.
Best wishes!
