### ISSUE TITLE
Building Astra on MAC OS X with CUDA and Conda

### ISSUE THREAD

**Issue by ravescovi** [astra-toolbox/astra-toolbox#39]
Hello all,

I am trying to build the current version in my conda env using osx10.11.

First bug, in this current cuda implementation there are no more lib64 folder in /usr/local/cuda. I have managed to install with a cp lib/* lib64 (mimicating the lib64 on normal linux machines). 

Then i was able to build libastra and astra-toolbox. But in the first test i have the following message.

===== testing package: astra-toolbox-1.8b-py27_0 =====
import: u'astra'
Traceback (most recent call last):
  File "/Users/vescovi/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import astra
  File "/Users/vescovi/anaconda/envs/_test/lib/python2.7/site-packages/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/Users/vescovi/anaconda/envs/_test/lib/python2.7/site-packages/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: dlopen(/Users/vescovi/anaconda/envs/_test/lib/python2.7/site-packages/astra/astra_c.so, 2): Library not loaded: /usr/local/lib/libastra.0.dylib
  Referenced from: /Users/vescovi/anaconda/envs/_test/lib/python2.7/site-packages/astra/astra_c.so
  Reason: image not found
TESTS FAILED: astra-toolbox-1.8b-py27_0

There are something wrong with the libraries bindings because i had to manually copy libastra.0.dylib to /usr/local/lib/. After that i moved to the following error.
>>> import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: dlopen(astra/astra_c.so, 2): Symbol not found: __ZN5astra25CCompositeGeometryManager18setGlobalGPUParamsERKNS_10SGPUParamsE
  Referenced from: astra/astra_c.so
  Expected in: /usr/local/lib/libastra.0.dylib
 in astra/astra_c.so

I am probably doing something wrong since it was not really straight forward to install the conda recipes.

Thanks,
Rafael

**Comment by wjp** [comment]
Hi,

We unfortunately don't have any access to OS X, so we can't try this ourselves. Which revision of astra are you trying exactly?

The last error you mention might indicate libastra.0.dylib was built without CUDA support. Could you verify this?

**Comment by ravescovi** [comment]
Here is the output of the configure file. Looks like everything is ok.
`visa43:linux vescovi$ ./configure --with-python --with-cuda=$CUDA_ROOT --prefix=$PREFIX
checking build system type... x86_64-apple-darwin15.4.0
checking host system type... x86_64-apple-darwin15.4.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.4.0 file names to x86_64-apple-darwin15.4.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.4.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... yes
checking iostream usability... yes
checking iostream presence... yes
checking for iostream... yes
checking for boost-unit-test-framework... yes, libboost_unit_test_framework-mt
checking boost/any.hpp usability... yes
checking boost/any.hpp presence... yes
checking for boost/any.hpp... yes
checking boost/static_assert.hpp usability... yes
checking boost/static_assert.hpp presence... yes
checking for boost/static_assert.hpp... yes
checking boost/throw_exception.hpp usability... yes
checking boost/throw_exception.hpp presence... yes
checking for boost/throw_exception.hpp... yes
checking for nvcc... /usr/local/cuda//bin/nvcc
checking for cudaMalloc in -lcudart... yes
checking for cufftPlan1d in -lcufft... yes
checking if nvcc works... yes
checking for nvcc archs... 20, 30, 35, 50
checking for python... python
checking for numpy module... yes
checking for Cython module... yes
checking for six module... yes
checking for scipy module... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: executing libtool commands

Summary of ASTRA Toolbox build options:
  CUDA   : yes
  Matlab : no
  Python : yes

  prefix : `


I also checked the raw output of the python make install-libraries and it looks like all the libraries are beign built correctly. Here is the code if anyone with a mac wanna try.

`export CUDA_ROOT='/usr/local/cuda/'
export LIBPATH='lib64'
export PREFIX='/Users/vescovi/Documents/workspace/astra_test/'
git clone https://github.com/ravescovi/astra-toolbox.git
cd astra-toolbox
cd build/linux
./autogen.sh
./configure --with-python --with-cuda=$CUDA_ROOT --prefix=$PREFIX
sudo make install-libraries python-root-install
sudo cp -P $CUDA_ROOT/$LIBPATH/libcudart* $PREFIX/lib
sudo cp -P $CUDA_ROOT/$LIBPATH/libcufft* $PREFIX/lib
`

**Comment by dmpelt** [comment]
Thanks for the configuration logs. I don't see anything strange in them at the moment.

I know I was able to create a working ASTRA library on OS X without CUDA (the machine I tested on did not have a CUDA-capable GPU), but that was a while ago. Can you try compiling without CUDA by simply not specifying CUDA_ROOT? It could be that CUDA on OS X works differently than on linux, which we may have to account for explicitly.

**Comment by AoxiangGeng** [comment]
Hello, 

We have also tried to install ASTRA on a MAC OS X. Just share our experience and problem here and hope it can help .

We followed the way :
git clone https://github.com/astra-toolbox/astra-toolbox astra
cd astra/
git branch -a
git checkout tags/v1.7.1
export CUDA_ROOT='/usr/local/cuda/'
echo $CUDA_ROOT
cd python/conda/
MAKEOPTS="-j 8" conda build ./
conda install --use-local astra-toolbox

But when we run MAKEOPTS="-j 8" conda build ./, there is an error says:
Package: astra-toolbox-1.7.1-py27_0
source tree in: /Users/ademortiere/anaconda/conda-bld/work

cd build/linux
./autogen.sh ./autogen.sh: line 20: glibtoolize: command not found Error running libtoolize Command failed: /bin/bash -x -e /Users/ademortiere/anaconda/astra/python/conda/build.sh

So we tried to install libtool with 'brew install libtool'; it returned : libtoolinstalled, it is just not linked.
But when we do 'brew link libtool, it returned:Error: Could not symlink include/libltdl/lt_dlloader.h
/usr/local/include/libltdl is not writable.
Even if we tried 'sudo brew link libtool' it still didn't work.

Then we figured out that MAC itself has installed libtool as glibtool, but simply change the name won't fix this problem.

@ravescovi Can you please tell us how do you modify the build.sh file? Thanks a lot.

**Comment by ravescovi** [comment]
Hey guys,
Sorry for the late answer.
I just runned ```brew list``` and got the following packages:
```
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 aspell
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 atk
drwxr-xr-x  3 vescovi  admin  102 Apr 11 10:38 autoconf
drwxr-xr-x  3 vescovi  admin  102 Apr 11 10:40 boost
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 cairo
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 enchant
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 fontconfig
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 freetype
drwxr-xr-x  3 vescovi  admin  102 Feb 23 20:08 gcc
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:38 gdbm
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 gdk-pixbuf
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:14 gedit
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:09 gettext
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:50 git
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:09 glib
drwxr-xr-x  3 vescovi  admin  102 Feb 23 20:06 gmp
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:13 gnome-icon-theme
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 gobject-introspection
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 gsettings-desktop-schemas
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 gtk+
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:11 gtk+3
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 gtk-mac-integration
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:13 gtksourceview3
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:11 harfbuzz
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:11 hicolor-icon-theme
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:11 icu4c
drwxr-xr-x  3 vescovi  admin  102 Feb 23 20:06 isl
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 iso-codes
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 jpeg
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 libepoxy
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:09 libffi
drwxr-xr-x  3 vescovi  admin  102 Feb 23 20:06 libmpc
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:13 libpeas
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 libpng
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 libtiff
drwxr-xr-x  3 vescovi  admin  102 Apr 11 10:38 libtool
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:13 libxml2
drwxr-xr-x  3 vescovi  admin  102 Feb 23 20:06 mpfr
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:38 openssl
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:11 pango
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:10 pixman
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:38 pkg-config
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 py2cairo
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 pygobject
drwxr-xr-x  3 vescovi  admin  102 Feb 23 22:12 pygtk
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:39 python
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:38 readline
drwxr-xr-x  3 vescovi  admin  102 Feb 23 19:38 sqlite
```
Check if boost, libtool, readline and autoconf are installed. The next problem you will run is that cuda installation on OSX has all the x86_64 libs at /lib and not /lib64. I just did a ```sudo cp /lib /lib64```.

and at the build.sh i added 

```
cp -P $CUDA_ROOT/$LIBPATH/libcudart.* $PREFIX/lib
cp -P $CUDA_ROOT/$LIBPATH/libcufft.* $PREFIX/lib
```
Which solves the naming problem.

**Comment by dmpelt** [comment]
I will try to find an OSX machine on which I can test, and hopefully also create conda packages for ASTRA. Based on some tests with @ravescovi, I think we will need to change a few things in the ASTRA building process to get it to compile and install correctly.

 I will report here once I get it working.

**Comment by physlin** [comment]
Hi everyone,

I know this is an old discussion, but I'm just wondering if anyone was finally able to get this working on OSX. Any success?

**Comment by kohr-h** [comment]
Hi, there are fresh changes in the build system, so if somebody with a Mac could give it a shot with the current master and give feedback, that would be good.
On Linux, the commands to build `libastra` (the C++ library) and `astra-toolbox` (the Python bindings) are (from repo root):
```bash
CC=/path/to/your/compiler CUDA_ROOT=/path/to/cuda conda build python/conda/libastra

CC=/path/to/your/compiler CUDA_ROOT=/path/to/cuda conda build python/conda
```
The second build has `libastra` (built in the first step) as *build dependency*, but that's okay since it will pick up the locally built package from the first step.

**Comment by physlin** [comment]
I've just tried this, and it seems to be falling over when running condo_build.sh, as it can't find true in /bin/true. On OS X it's in /usr/bin, and it's not possible to create a symlink in /bin as El Capitan does not allow changes there even with sudo.

**Comment by wjp** [comment]
You should be able to edit `python/conda/libastra/build.sh` in astra, and replace the `/bin/true` there by `/usr/bin/true`.

**Comment by physlin** [comment]
Thanks. Sorry, I probably commented a bit too early. I did do that, but then I ran into other problems. I've since decided to just dual boot Linux to save time.

**Comment by djorlando24** [comment]
Update on this issue as of Jan 2018.. successfully built astra with CUDA on MacOS 10.12 using clang 8.1.0 and CUDA-9.1.  Had to downgrade my clang to make CUDA happy. 

The build succeeds without error, but then this happens when you try to test:

```
$ python -c 'import astra'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dduke/miniconda2/lib/python2.7/site-packages/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/Users/dduke/miniconda2/lib/python2.7/site-packages/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: dlopen(/Users/dduke/miniconda2/lib/python2.7/site-packages/astra/astra_c.so, 2): Symbol not found: __ZN5astra13cudaAvailableEv
  Referenced from: /Users/dduke/miniconda2/lib/python2.7/site-packages/astra/astra_c.so
  Expected in: flat namespace
 in /Users/dduke/miniconda2/lib/python2.7/site-packages/astra/astra_c.so
```

I have to manually do 
```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HOME/miniconda2/lib/python2.7/site-packages/astra
```
to circumvent the problem. This is not good practice. We need to get the right RPATH set at build time for these libs, so that MacOS knows where to look for them.  That's not something I know how to do personally, but I'm happy to help debug.

**Comment by theantisnear** [comment]
I am running into the same error as djorlando. Upon using his suggested fix, on import in python i get the error
'
  File "<stdin>", line 1, in <module>
  File "astra.py", line 26, in <module>
    from . import astra_c as a
ValueError: Attempted relative import in non-package
'

Changing to the python path as suggested [here](https://github.com/astra-toolbox/astra-toolbox/issues/11) did not change the error message.
