### ISSUE TITLE
Use of function deprecated in NumPy when accessing the projection matrix as a Scipy sparse matrix

### ISSUE THREAD

**Issue by effepivi** [astra-toolbox/astra-toolbox#428]
Hello,

I get the error below on Line  42 of `samples/python/s009_projection_matrix.py`

I have python 3.10.13, astra-toolbox 2.1.2, numpy 1.26.2.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fpvidal/miniconda3/envs/astra/lib/python3.10/site-packages/astra/matrix.py", line 80, in get
    return m.get(i)
  File "astra/matrix_c.pyx", line 118, in astra.matrix_c.get
  File "astra/matrix_c.pyx", line 75, in astra.matrix_c.astra_to_csr_matrix
  File "/home/fpvidal/miniconda3/envs/astra/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by askorikov** [comment]
We'll publish this release once it's been tested on all platforms, that's why it's it's labeled as a development version until then. Also note that we so far are only publishing minor versions (like 2.1.0, 2.2,0) as GitHub releases, and not patches (like 2.1.2, 2.1.3).

Installation via conda is recommended for Python, because it automates the process, installs all required dependencies of correct versions and allows for creating isolated environments with different versions of the same package if needed.
