### ISSUE TITLE
Unknow algorithm error after updating Astra

### ISSUE THREAD

**Issue by nghia-vo** [astra-toolbox/astra-toolbox#461]
I used the below codes and they work fine until I've updated to astra 2.1.2 (python 3.11, WinOS).

```python
import numpy as np
import scipy
import astra


def astra_reconstruction(sinogram, center, angles, method, filter_name,
                         num_iter):
    ncol = sinogram.shape[-1]
    proj_geom = astra.create_proj_geom('parallel', 1, ncol, angles)
    vol_geom = astra.create_vol_geom(ncol, ncol)
    cen_col = (ncol - 1.0) / 2.0
    sinogram = scipy.ndimage.shift(sinogram, (0, cen_col - center),
                                   mode='nearest')
    sino_id = astra.data2d.create('-sino', proj_geom, sinogram)
    rec_id = astra.data2d.create('-vol', vol_geom)
    proj_id = None
    if "CUDA" not in method:
        proj_id = astra.create_projector('line', proj_geom, vol_geom)
    cfg = astra.astra_dict(method)
    cfg['ProjectionDataId'] = sino_id
    cfg['ReconstructionDataId'] = rec_id
    if "CUDA" not in method:
        cfg['ProjectorId'] = proj_id
    if (method == "FBP_CUDA") or (method == "FBP"):
        cfg["FilterType"] = filter_name
    try:
        alg_id = astra.algorithm.create(cfg)
    except Exception:
        raise ValueError("Invalid selection of method!!!")
    astra.algorithm.run(alg_id, num_iter)
    recon = astra.data2d.get(rec_id)
    astra.algorithm.delete(alg_id)
    astra.data2d.delete(sino_id)
    astra.data2d.delete(rec_id)
    return recon

sinogram = np.random.rand(200, 600)
angles = np.deg2rad(np.linspace(0.0, 180.0, 200))
img_rec = astra_reconstruction(sinogram, 300, angles, "FBP_CUDA", "hann",1)
```
Got the following error:
```
Traceback (most recent call last):
  File "C:\check_codes\astra_error.py", line 27, in astra_reconstruction
    alg_id = astra.algorithm.create(cfg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\site-packages\astra\algorithm.py", line 36, in create
    return a.create(config)
           ^^^^^^^^^^^^^^^^
  File "astra\\algorithm_c.pyx", line 64, in astra.algorithm_c.create
Exception: Unknown Algorithm.
```

Same problem if I choose "SIRT_CUDA". However, works fine if I use "FBP" or "SIRT".

**Comment by askorikov** [comment]
Hi! You probably have CPU-only version of Astra installed from conda-forge. Installing the CUDA version with `conda install astra-toolbox=*=cuda*` should solve this.

**Comment by askorikov** [comment]
Hi @carterbox, I can reproduce that currently conda resolves `astra-toolbox` from `conda-forge` to CPU-only build by default. On the other hand, solving for purely `libastra` correctly prioritizes the CUDA build. Can it be related to [this issue of the currently default libmamba solver](https://conda.github.io/conda-libmamba-solver/user-guide/libmamba-vs-classic/#cudatoolkit-present-in-a-cpuonly-environment)? Although at the moment the classic solver doesn't work as expected either. In any case, I wonder if moving the `track_features` to the `astra-toolbox` recipe could solve this problem?

**Comment by nghia-vo** [comment]
I installed astra-toolbox:
```
conda install -c astra-toolbox astra-toolbox
```
got this:
```
The following packages will be UPDATED:

  astra-toolbox                 2.1.0-cudapy311hb5d74c7_105 --> 2.1.2-py311h8745f56_0
  libastra           astra-toolbox::libastra-2.1.0-cuda_11~ --> conda-forge::libastra-2.1.2-hbc5358b_1
```
Then using your instruction:
```
conda install -c astra-toolbox astra-toolbox=*=cuda*
```
got this:
```
  added / updated specs:
    - astra-toolbox[build=cuda*]


The following packages will be SUPERSEDED by a higher-priority channel:

  libastra           conda-forge::libastra-2.1.2-hbc5358b_1 --> astra-toolbox::libastra-2.1.0-cuda_11.3_0

The following packages will be DOWNGRADED:

  astra-toolbox                       2.1.2-py311h8745f56_0 --> 2.1.0-cudapy311hb5d74c7_105
```
Then I can't import astra. 

```
Traceback (most recent call last):
    import astra
  File "C:\Users\Lib\site-packages\astra\__init__.py", line 26, in <module>
    from . import matlab as m
  File "C:\Users\\Lib\site-packages\astra\matlab.py", line 38, in <module>
    from . import astra_c
ImportError: DLL load failed while importing astra_c: The specified module could not be found.
```

**Comment by askorikov** [comment]
I think the problem now is that `astra-toolbox` and `libastra` from astra-toolbox and conda-forge channels are mixed. I sort of assumed that you have conda-forge as a default channel, so if it's not the case the full command should be `conda install astra-toolbox=*=cuda* libastra -c conda-forge`. On the other hand, if you want to use the astra-toolbox channel, you should update the `libastra` package as well like `conda install astra-toolbox libastra -c astra-toolbox`, otherwise there will be DLL incompatibility issues that you see. This mixing between `astra-toolbox` and `libastra` from different channels should not happen when creating a fresh conda environment, but maybe we should try to come up with a mechanism to avoid it in more general cases.

**Comment by nghia-vo** [comment]
Many thanks Alex. I followed the instruction on the astra documentation page where the astra-toolbox channel is used instead of conda-forge: https://astra-toolbox.com/downloads/2.1.0/index.html. Will update how things go after cleaning.

**Comment by carterbox** [comment]
It seems that the CUDA builds of `astra-toolbox=2.1.2` do not exist from conda-forge which is why you cannot install them.

```
conda search libastra=2.1.2
Loading channels: done
# Name                       Version           Build  Channel             
libastra                       2.1.2 cuda11.2h7a2a054_101  conda-forge         
libastra                       2.1.2 cuda11.2hdc79366_100  conda-forge         
libastra                       2.1.2 cuda11.8he3cf3a2_101  conda-forge         
libastra                       2.1.2 cuda11.8hfebff79_100  conda-forge         
libastra                       2.1.2      h00f6aea_0  conda-forge         
libastra                       2.1.2      ha94a2df_1  conda-forge         

conda search astra-toolbox=2.1.2
Loading channels: done
# Name                       Version           Build  Channel             
astra-toolbox                  2.1.2 py310hf72850d_0  conda-forge         
astra-toolbox                  2.1.2 py311h6364c26_0  conda-forge         
astra-toolbox                  2.1.2 py312haa756ed_0  conda-forge         
astra-toolbox                  2.1.2  py38h010e5b0_0  conda-forge         
astra-toolbox                  2.1.2  py39h9f90943_0  conda-forge   
```
I'll have to update the feedstock. Everything should behave normally for 2.1.0.

**Comment by askorikov** [comment]
Oh, this makes more sense. I haven't thought about that.

**Comment by askorikov** [comment]
It's fixed now. Thanks @carterbox!

**Comment by nghia-vo** [comment]
I created new environment, installed astra-toolbox using conda-forge. Still run into the same problem.
```
The following NEW packages will be INSTALLED:

  astra-toolbox      conda-forge/win-64::astra-toolbox-2.1.2-cudapy310h5e715df_101
  cudatoolkit        conda-forge/win-64::cudatoolkit-11.8.0-h09e9e62_13
  libastra           conda-forge/win-64::libastra-2.1.2-cuda11.8h413fb23_101
  libboost           pkgs/main/win-64::libboost-1.82.0-h3399ecb_2
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
```

**Comment by carterbox** [comment]
I wasn't able to reproduce your problem on my Windows computer using the same astra packages.

```
(test) PS C:\Users\dchin\Documents> conda list
# packages in environment at C:\Users\dchin\miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
astra-toolbox             2.1.2           cudapy310h5e715df_101    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cuda-version              11.8                 h70ddcb2_3    conda-forge
cudatoolkit               11.8.0              h09e9e62_13    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
libastra                  2.1.2           cuda11.8h413fb23_101    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libboost                  1.82.0               h65993cd_6    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libsqlite                 3.45.2               hcfcfb64_0    conda-forge
libxml2                   2.12.6               hc3477c8_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
numpy                     1.26.4          py310hf667824_0    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
scipy                     1.12.0          py310hf667824_2    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tbb                       2021.11.0            h91493d7_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.43.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

You have a package from defaults in your environment.

> libboost           pkgs/main/win-64::libboost-1.82.0-h3399ecb_2

As a reminder, conda-forge does not support mixing with packages from other channels.

**Comment by nghia-vo** [comment]
It works now. Thanks a lot Daniel, Alex.
