### ISSUE TITLE
Astra in python package index

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#51]
Adding astra to Python Package Index (PyPI) would allow users to install ASTRA by simply writing:

```
pip install astra-tomography
```

Sadly, there is a package named [astra](https://pypi.python.org/pypi/astra/) in PyPI already, but adding astra as `astra-tomography` would still be nice.

The main steps you need to do in order to enable this is:

* Create an astra account on PyPI (simple and free)
* Write a setup.py file that fully performs the build rutine of astra, perhaps by calling other files.

I feel that by doing this you would significantly widen the user base of ASTRA by allowing more "simple" users to simply download astra in one command and instantly get started!

**Comment by dmpelt** [comment]
In conda we use `astra-toolbox` as the package name, we could use that for PyPI as well. A potential issue that we could have is that the python interface requires the compilation of the C++ library first through a `./configure` and `make` step, and a `python setup.py ...` afterwards. I don't know whether PyPI supports such a build system (I could not get readthedocs to compile it correctly for example). I will look into it, it has been on my todo list for a while, but I wrote the conda build scripts first since it supports our build system better. A `setup.py` file that fully performs the build routine by making external `configure` and `make` calls is possible, but it feels a bit hacky. Do you know other PyPI packages that have the same problems and a common solution for it?

**Comment by adler-j** [comment]
Numpy obviously has exactly the same issue and solves it by simply having an enormous `setup.py` file that does everything. Otherwise python wheels are supposed to enable you to distribute pre-built binaries for some platforms (notably windows).

**Comment by dmpelt** [comment]
I've created PyPI build files in #53, and uploaded a PyPI package [here](https://pypi.python.org/pypi?:action=display&name=astra-toolbox). It was quite difficult to get PyPI working with building a shared C++ library first and linking the python C extension files to it correctly. I think this might be a bit different compared with numpy, where the external code is compiled into the C extension files itself if I understand correctly. Anyway, the following should work now:
```bash
CUDA_ROOT=/path/to/cuda MAKEOPTS="-j 16" pip install astra-toolbox
```
Or, without CUDA and slower compilation, simply:
```bash
pip install astra-toolbox
```

**Comment by pylipp** [comment]
@dmpelt There's a bug in the `setup.py`. The kwarg `include_dirs` of the final `setup()` call needs to be set to the list `incdirs` that was defined before. Otherwise the numpy headers won't be found.

I'm still having trouble to run astra though. I downloaded the PyPI package into a virtualenv. I run 
```
pip install -r requirements.txt
```
(copied from your pull-request because the file is missing in the package, maybe you meant to include it) and finally
```
python setup.py install
```
I modified the LD_LIBRARY_PATH and PYTHONPATH variables as suggested. Still when I run `import astra` I get an ImportError: cannot import name astra_c. 
Do you have any suggestions or recommendations of setting things up differently?
I'm running Lubuntu 14.04 without cuda or matlab.

**Comment by pylipp** [comment]
Sorry for the mess. To sum up, my modifications were 
- adding [requirements.txt](https://github.com/dmpelt/astra-toolbox/blob/pypi/python/pypi/requirements.txt) to the extracted PyPI package
- running `pip install -r requirements.txt`
- modifying setup.py as described above
- run `python setup.py install`

**Comment by dmpelt** [comment]
Thanks for the report!

Indeed, I forgot to actually use the correct variable in `include_dirs` and to include `requirements.txt` in the package. I fixed it in the PR and uploaded a new package to PyPI. The `--with-python` argument in `confcall` is actually not needed, since the C++ library can be built without Python support, even when linking it to Python later (after cd395d2).

If you have time, can you try a `pip install astra-toolbox` in a clean environment to see whether it works out of the box now? It may take a while for PyPI to update the packages, the correct new version should be `1.8b5`.

**Comment by pylipp** [comment]
Thank you for the quick reply.
I was able to successfully build the package in a clean virtualenv by `pip install --no-cache-dir astra-toolbox`. It is version 1.8b5.
Without the `--no-cache-dir` option, I was given an error that `cythonize` is not defined in `setup.py`. Maybe importing `Cython` failed before for some reason. 
Should we add the installation procedure to the documentation? I can sum up my experiences if you point me to where I should put it.

**Comment by dmpelt** [comment]
I think pip was still using the old version when `--no-cache-dir` was not specified, and Cython was not installed in your pip environment, which caused the `cythontize` error (since I forgot to add `requirements.txt`, the old package did not install cython automatically). The new version should correctly install all required packages.

I am glad the new version works correctly. Once #53 is merged, we will add some documentation to the website.

Thanks for testing it!

@adler-j Does it work on your machine as well?

**Comment by arsenal9971** [comment]
Hi @dmpelt I am trying to install astra-toolbox in an OSX, this is due it is a required library for the package made by @adler-j. I am doing it in a virtualenv, I don't want to do it with conda, since I don't like conda (it leads to a lot of problems with library locations). 

I tried to do this by `pip install astra-toolbox` but it fails. So I did by building the library with the next lines
```
CPPFLAGS="-I/usr/local/include" NVCCFLAGS="-I/usr/local/include" ./configure \
  --with-python=/Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/bin/python \
  --with-install-type=module
```

(it is worth to mention as it is visible that I am not building it wiht cuda, since I don't have cuda) now it does not fail on building, but it seems that some headers, in particular libastra.0.dylib are pointing to a directory where they aren't. This is clear, cause when I am importing in the python REPL astra as ` import astra`, I get the error:

```
ImportError: dlopen(/Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/lib/python2.7/site-packages/astra/astra_c.so, 2): Library not loaded: /usr/local/lib/libastra.0.dylib
  Referenced from: /Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/lib/python2.7/site-packages/astra/astra_c.so
  Reason: image not found
```

This happens since I am trying install it in the virtual environment so the library libastra.0.dylib is located in a subdirectory of the virtualenviroment. Now doing what is suggester in
https://github.com/astra-toolbox/astra-toolbox/issues/39#issuecomment-360124824. Now when I am doing this I still get the error in a new form:

```
ImportError: dlopen(/Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/lib/python2.7/site-packages/astra/utils.so, 2): Symbol not found: __ZN5astra6Config10initializeENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  Referenced from: /Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/lib/python2.7/site-packages/astra/utils.so
  Expected in: flat namespace
 in /Users/hector/Documents/Learning_new_languages/learning_TensorFlow/tensorflow/lib/python2.7/site-packages/astra/utils.so
```

I don't really know what I am doing wrong, any suggestions?, having a stable pip installer will solve my problem I think. I actually already installed astra in a virtualenv on linux using the same procedure and it worked.

**Comment by zaccharieramzi** [comment]
Hi,

Installing with `pip` also failed for me with:

```python
Running setup.py clean for astra-toolbox
  ERROR: Complete output from command /home/zaccharie/workspace/learned_primal_dual/venv/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nn03k4b9/astra-toolbox/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: ./autogen.sh: ligne 3: aclocal : commande introuvable
  Error running aclocal
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-nn03k4b9/astra-toolbox/setup.py", line 80, in <module>
      subprocess.call(confcall)
    File "/usr/lib/python3.6/subprocess.py", line 267, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: './configure': './configure'
  ----------------------------------------
  ERROR: Failed cleaning build dir for astra-toolbox
Failed to build astra-toolbox
```

**Comment by kohr-h** [comment]
`ERROR: ./autogen.sh: ligne 3: aclocal : commande introuvable`

You need the `automake` package on your system (perhaps others). Usually it's easiest to install `build-essential` if you're on a Debian-like system (Ubuntu, ...), that gives you the whole bunch.

**Comment by zaccharieramzi** [comment]
Yes I found that out later when installing it from source. I guess there is a need for a documentation on the dependencies when installing with pip.

**Comment by aisosalo** [comment]
Would it be possible to get more recent than [astra-toolbox 1.8b5](https://pypi.org/project/astra-toolbox/) to the Python Package Index? That would make life easier with setups without the option to install via conda.

**Comment by ToruHironaka** [comment]
I could install astra-toolbox 1.8b5 successfully. I think astra.test() function is missing. I could find many other functions though. 

Missing astra,test()

![image](https://user-images.githubusercontent.com/6956496/183220273-80661917-7e75-4b37-8539-2b5ddb0c9874.png)

Other astra functions.
![image](https://user-images.githubusercontent.com/6956496/183220518-40ae6210-6761-4fcf-a1a1-1eaf82157d58.png)

**Comment by askorikov** [comment]
Hi all! Since version 2.2, we are distributing a PyPI package for Linux that makes use of `nvidia-cuda-runtime-cu12`, `nvidia-cufft-cu12` as dependencies. This should enable most of the the use cases listed in the comment above.

However, it's tricky to distribute a Windows package, since the shared libraries installed via pip are not added to the PATH and cannot be reliably used as dependencies. We can't bundle these dependencies with ASTRA (like PyTorch does, for example) because of package size limits, but we could provide an ASTRA package nevertheless, expecting that the user installs the CUDA Toolkit manually (like CuPy does). Let us know in this issue if such a distribution would be useful for you.

**Comment by moritz-h** [comment]
> Let us know in this issue if such a distribution would be useful for you.

@askorikov I think this would be very helpful. I'm using astra-toolbox in a cross platform application and currently manually installing the wheel from the homepage to the venv on Windows systems. Just adding it to requirements.txt would be so much more convenient for users of the tool.

I saw that the Windows wheel from you homepage also just distributes the cuda dlls. With looking a bit into the problem I just found that there is [os.add_dll_directory()](https://docs.python.org/3/library/os.html#os.add_dll_directory) since Python 3.8. This sounds like it may could solve the PATH problem when using the official Cuda packages from PyPI.

I did some quick testing and it seems to work: I created a new empty venv, installed the wheel from the astra homepage, moved all cuda dlls to separate folder.
Now just `import astra` fails due to the missing cuda dlls, but this seems to work:
```python
import os
with os.add_dll_directory('C:\\path\\to\\cuda\\dlls'):
    import astra
print(astra.astra.use_cuda())
```

**Comment by askorikov** [comment]
@moritz-h By the way, could you maybe share why you would prefer to install astra via pip? Just for us to understand the use cases better.

**Comment by carterbox** [comment]
The basic concept for using CTK wheels is that you pre-load the CTK wheel libraries into the processes before you load your own libraries. By doing this, you can control from where a library is loaded (unless it was already loaded by another library) because the OS won't load multiple libraries of the same name. NVIDIA CUDA wheels are somewhat new, but we are developing [`cuda-pathfinder`](https://github.com/NVIDIA/cuda-python/tree/main/cuda_pathfinder/cuda/pathfinder) for this purpose.

Otherwise, you can implement your own logic which tries to find each library in site-packages and load them using [`ctypes.cdll`](https://docs.python.org/3/library/ctypes.html). This is what `nvmath-python` does currently, but we plan to migrate to `cuda-pathfinder`.

**Comment by carterbox** [comment]
> For me, if all my depedencies are python packages, it feels annoying to have to install an additional external package manager on my system instead of just using a lightweight venv which can be setup with pure Python.

@moritz-h, the WheelNext (https://wheelnext.dev/) initiative may be of interest to you and needs your support. In summary, developers like yourself want the convenience of using only pip to manage dependencies for python package, but the wheel format wasn't designed for non-python dependencies (like the CTK, MPI, or BLAS). WheelNext is trying to bring new features to the wheel format and python package managers, so they can handle the extra nuances packaging C shared libraries inside wheels.

> Some other dependencies I want to use in the same project are only available on PyPI.

conda-forge is community maintained, so you [can migrate python packages](https://conda-forge.org/docs/maintainer/adding_pkgs/) from PyPI to conda.
