### ISSUE TITLE
MPI: overflow when initializing large object with (local) array

### ISSUE THREAD

**Issue by wjp** [astra-toolbox/astra-toolbox#67]
```
  File "astra/data3d_c.pyx", line 187, in astra.data3d_c.create (astra/data3d_c.cpp:4000)
  File "astra/data3d_c.pyx", line 424, in astra.data3d_c.fillDataObject (astra/data3d_c.cpp:7317)
  File "MPI/Comm.pyx", line 1175, in mpi4py.MPI.Comm.send (src/mpi4py.MPI.c:106424)
  File "MPI/msgpickle.pxi", line 210, in mpi4py.MPI.PyMPI_send (src/mpi4py.MPI.c:42085)
  File "MPI/msgpickle.pxi", line 112, in mpi4py.MPI.Pickle.dump (src/mpi4py.MPI.c:40704)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

This exception is triggered when sending an object larger than 4 GB, but in fact sending an object larger than 2GB already seems to trigger an overflow bug in mpi4py,

**Comment by codeling** [comment]
I'm trying to reconstruct 6GB projection data with the 1.7.1 MPI version, and I get a similar error (though not exactly the same):
```
Traceback (most recent call last):
  File "./toolbox.py", line 59, in <module>
    exec(code)
  File "../test_MiCi_reco.py", line 33, in <module>
    proj_id = astra.data3d.create('-sino', proj_geom, sinogram)
  File "/home/test/astra_distr_py3/python/astra/data3d.py", line 41, in create
    return d.create(datatype,geometry,data)
  File "astra/data3d_c.pyx", line 187, in astra.data3d_c.create
  File "astra/data3d_c.pyx", line 424, in astra.data3d_c.fillDataObject
  File "mpi4py/MPI/Comm.pyx", line 1156, in mpi4py.MPI.Comm.send
  File "mpi4py/MPI/msgpickle.pxi", line 174, in mpi4py.MPI.PyMPI_send
  File "mpi4py/MPI/msgpickle.pxi", line 106, in mpi4py.MPI.Pickle.dump
  File "mpi4py/MPI/msgbuffer.pxi", line 45, in mpi4py.MPI.downcast
OverflowError: integer 2162786469 does not fit in 'int'
```
Is this the same/ a related issue ? Is there a workaround?
I'm running these experiments on python 3.5 under ubuntu 16.04.
